### PR TITLE
Add Display offer implementation

### LINKED ISSUE #186: Impl `Display` on `Offer`
Currently only `Debug` is implemented on `Offer`.

### PR DESCRIPTION
**Pull request by h4sh3d**
Fix #186

Implements `fmt::Display` on `Offer` along other types. Change some `ToString` impl with proper `Display` for better genericity.

~Relax clippy warnings and add msrv in case of new breaking rules.~

### CODE REVIEW

**Comment by TheCharlatan** [comment]
LGTM so far, but didn't we want to include the exchange rate of the two assets?

**Comment by h4sh3d** [comment]
You would compute automatically when calling display? I thought this should be the user of Offer to decide if/when computing the rate and display it, i.e. in the cli node.

**Comment by h4sh3d** [comment]
What I mean is: I don't think it is the responsibility of `Display` to do computation.

**Review by TheCharlatan — APPROVED** [review]
That's fair enough.

**Pull request merged**
