### PR TITLE
Bump lnp/bp dependencies for dependency allignment

### PR DESCRIPTION
**Pull request by TheCharlatan**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Seems like there is some weird behavior around nightly builds.

**Comment by Lederstrumpf** [comment]
When compiling on `stable`:
```
error: package `lightning_encoding v0.5.13` cannot be built because it requires rustc 1.56.1 or newer, while the currently active rustc version is 1.56.0
```
And the CLI is currently on 1.54.0, so that's part of the issue.

**Comment by Lederstrumpf** [comment]
On both `rustc 1.59.0` and `rustc 1.61.0-nightly`, I get the following issue then:

```
   Compiling lightning_encoding v0.5.13
error[E0599]: no method named `to_be_bytes` found for reference `&u24` in the current scope
  --> /home/lederstrumpf/.cargo/registry/src/github.com-1ecc6299db9ec823/lightning_encoding-0.5.13/src/primitives.rs:56:26
   |
56 |         let bytes = self.to_be_bytes();
   |                          ^^^^^^^^^^^ help: there is an associated function with a similar name: `to_le_bytes`

error[E0599]: no function or associated item named `from_be_bytes` found for struct `u24` in the current scope
  --> /home/lederstrumpf/.cargo/registry/src/github.com-1ecc6299db9ec823/lightning_encoding-0.5.13/src/primitives.rs:66:17
   |
66 |         Ok(u24::from_be_bytes(buf))
   |                 ^^^^^^^^^^^^^
   |                 |
   |                 function or associated item not found in `u24`
   |                 help: there is an associated function with a similar name: `from_le_bytes`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `lightning_encoding` due to 2 previous errors
```

**Comment by TheCharlatan** [comment]
Works for me with rustc 1.59.0 . Maybe remove your Cargo.lock and target/ and try again?

**Comment by Lederstrumpf** [comment]
> Works for me with rustc 1.59.0 . Maybe remove your Cargo.lock and target/ and try again?

ah yeah, forgot to remove lock file 🙈 - thanks!
Confirm working for me with rustc 1.59.0 as well now. So if CI is updated, all should be good and we can merge your PR.

**Review by Lederstrumpf — APPROVED** [review]

**Pull request merged**
